version: '3'
services:
  api:
    user: "1000:1000"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - .:/app
      - .bundle:/usr/local/bundle
    env_file: .env
    stdin_open: true
    tty: true

  frontend:
    user: "node"
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules

volumes:
  bundle:
  node_modules:
